// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	validator "github.com/monitoror/monitoror/internal/pkg/validator"
)

// ParamsValidator is an autogenerated mock type for the ParamsValidator type
type ParamsValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *ParamsValidator) Validate() []validator.Error {
	ret := _m.Called()

	var r0 []validator.Error
	if rf, ok := ret.Get(0).(func() []validator.Error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]validator.Error)
		}
	}

	return r0
}
